### ISSUE TITLE
internal edges should not be styled with speeds

### ISSUE THREAD

**Issue by drewda** [opentraffic/analyst-ui#119]
An example provided by Duane: http://opentraffic-ui.netlify.com/?lat=14.6021&lng=121.0654&zoom=17.2500&df=0%2F7&hf=0%2F24&waypoints=14.6007%2F121.0649%2C14.5993%2F121.0695

![2017-09-25_11-00-16](https://user-images.githubusercontent.com/212369/30823472-180c01a0-a1e1-11e7-8baf-5d8b546b8876.png)

This is an internal edge, so it should not be styled with a speed. Plus, anyways, it shouldn't be styled in this screenshot, since a timeframe hasn't yet been specified.

//cc @dgearhart @louh

**Comment by drewda** [comment]
That segment gets speed=2 assigned by https://github.com/opentraffic/analyst-ui/blob/5dae2dc2e580fa03d273159e030677eb229100f1/src/app/route.js#L125-L129

Is that condition even still relevant? Should we just remove it?

**Comment by louh** [comment]
i propose removing it. we needed elapsed time to calculate ETA, but it is not relevant for the view because it is essentially "estimated" data as opposed to "actual" data.

**Comment by louh** [comment]
a7e1291939676b2adbebab9be3f92c9611ae4758
