### ISSUE TITLE
Download and parse "reference speed" tiles

### ISSUE THREAD

**Issue by drewda** [opentraffic/analyst-ui#120]
Open Traffic Datastore now generates both weekly speed tiles and "reference speed" tiles. The reference speed tiles include speed values for all 168 hours of a week, which are calculated to represent a weighted mean of all speeds known across all time for each segment.

Analyst UI will download and parse both weekly and reference speed tiles, in order to support comparisons between the two (see #108)

**Comment by louh** [comment]
https://github.com/opentraffic/analyst-ui/commit/0badd8f1b8cd1eafe2135d20684a18f800e4228a
