### ISSUE TITLE
Routes being rendered as gray when not zero speed

### ISSUE THREAD

**Issue by mkong0216** [opentraffic/analyst-ui#144]
<img width="1280" alt="screen shot 2017-10-04 at 10 19 18 am" src="https://user-images.githubusercontent.com/17012261/31182785-d5d07708-a8f2-11e7-9ae2-1b7e579893b7.png">

It looks like a gray route is overlapping almost completely a colored part. The colored part has the right color to match the speed. This might be due to how the offset shader is implemented, which I'm not sure how to fix. @drewda Maybe you'll have a better understanding of this?

**Comment by drewda** [comment]
Looping in @meetar to help...

**Comment by meetar** [comment]
url to replicate:

http://localhost:3000/?lat=14.6425&lng=121.0353&zoom=19.0000&df=0%2F7&hf=0%2F24&startDate=1483344000000&endDate=1483948799999&rn=14.645168&rs=14.640445&re=121.039596&rw=121.032246
