### ISSUE TITLE
export speeds at multiple hours

### ISSUE THREAD

**Issue by drewda** [opentraffic/analyst-ui#151]
At present, a GeoJSON export includes a single speed property for each segment. This is the average speed across any hours-of-day and days-of-week currently set in the time filter (on the bar chart).

The requested addition to be able to export speeds at each one of the hours-of-week within the time filters. There are a couple different ways we can implement this:

- in existing GeoJSON exports, add additional properties to each segment that give the segment speed at every possible selected hour
- allow export to a separate CSV file, which would give segment speeds at each selected hour

**Comment by mkong0216** [comment]
Closed via pull #153
