### ISSUE TITLE
Fetch OSMLR segment geometries

### ISSUE THREAD

**Issue by louh** [opentraffic/analyst-ui#22]
...when given OSMLR tile ids

**Comment by louh** [comment]
Also, when given a route, send the route geometry into the Map Matching `trace_attributes` action. From that 2nd request, you should get OSMLR segment IDs

**Comment by drewda** [comment]
OSMLR geometries are available in GeoJSON files on S3 at http://osmlr-tiles.s3.amazonaws.com/v0.1/geojson/ The tile files follow the Valhalla tile scheme.

**Comment by louh** [comment]
@drewda Say more about the Valhalla tile scheme? Or link to a resource describing what this scheme is?

**Comment by louh** [comment]
OK, I see from your comment in #23 what it looks like.

```
http://osmlr-tiles.s3.amazonaws.com/v0.1/geojson/0/002/415.json
```

For level 2 tiles, are the IDs always zero-padded to 9 digits?
For level 0 and level 1 tiles, are the IDs always zero-padded to 6 digits?

**Comment by kevinkreiser** [comment]
heres some code to generate the last part of a url:

```python
#!/usr/bin/env python
import math
valhalla_tiles = [{'level': 2, 'size': 0.25}, {'level': 1, 'size': 1.0}, {'level': 0, 'size': 4.0}]

def url_suffix(tile_level, tile_id):
  #get the right tile_set definition for level we want
  tile_set = filter(lambda x: x['level'] == tile_level, valhalla_tiles)[0]
  #get the maximum tile_id for that tile_set
  max_id = int(360.0/tile_set['size'] * 180.0/tile_set['size']) - 1
  #get the number of directories, we need 3 digits per directory
  num_dirs = int(math.ceil(len(str(max_id)) / 3.0))
  #zero pad the string of the number so it has the proper amount of digits
  suffix = list(str(tile_id).zfill(3 * num_dirs))
  #add in the directory separators
  for i in range(0, num_dirs):
    suffix.insert(i * 3 + i, '/')
  #add in the level at the beginning and turn the list back into a string
  suffix = '/' + str(tile_level) + ''.join(suffix) 
  return suffix


print url_suffix(2, 1036752)
print url_suffix(2, 42)
print url_suffix(1, 54)
print url_suffix(1, 64001)
print url_suffix(0, 79)
print url_suffix(0, 4001)
```

**Comment by louh** [comment]
@drewda Can you add CORS headers to the files in http://osmlr-tiles.s3.amazonaws.com/v0.1/geojson/?

**Comment by louh** [comment]
Sample script for fetching and merging geojson files: https://gist.github.com/drewda/5625cc82fecc3e217126d72f47f6e323

**Comment by drewda** [comment]
@louh I just turned on "static website hosting" on the `osmlr-tiles` bucket and set the CORS config to:

```xml
<CORSConfiguration>
	<CORSRule>
		<AllowedOrigin>*</AllowedOrigin>
		<AllowedMethod>GET</AllowedMethod>
		<MaxAgeSeconds>3000</MaxAgeSeconds>
		<AllowedHeader>Authorization</AllowedHeader>
	</CORSRule>
</CORSConfiguration>
```

**Comment by louh** [comment]
Thank you @drewda. The CORS configuration is now working for the geometries.

**Comment by louh** [comment]
Leaving a quick note for myself: the `geojson-merge` package has a dependency `JSONStream` with improper JS syntax, which breaks Webpack. JSONStream's maintainer refuses to fix this, claiming this to be a bug in Webpack (https://github.com/dominictarr/JSONStream/issues/126). I will need to decide on a workaround.

**Comment by louh** [comment]
Follow up: The `geojson-*` tools in Mapbox's namespace are quite simple, and we do not actually depend on streams, so the simplest thing to do in this case is to port Mapbox's merge code to the application and remove the dependency on `JSONStream` entirely.
