### ISSUE TITLE
Render OSMLR segment geometries

### ISSUE THREAD

**Issue by louh** [opentraffic/analyst-ui#23]

**Comment by drewda** [comment]
If you'd like to test rendering OSMLR segments in Manila, here's a way to fetch and merge together those tiles locally: https://gist.github.com/drewda/5625cc82fecc3e217126d72f47f6e323

**Comment by louh** [comment]
TODO: determine what ids from the `trace_attributes` query matches with the properties in each geoJSON feature. (It doesn't appear to be `osmlr_id`, based on trying to retrieve one of the `trace_attributes.traffic_segments[x].segment_id` values.
