### ISSUE TITLE
Parse OpenTraffic data tiles

### ISSUE THREAD

**Issue by louh** [opentraffic/analyst-ui#25]
See here for file structure. https://github.com/opentraffic/analyst-ui/wiki/opentraffic-data-tile-format

**Comment by drewda** [comment]
Related: https://github.com/opentraffic/datastore/issues/36

**Comment by louh** [comment]
Given an array of segment ids from a `trace_attributes` response, I obtained the appropriate OpenTraffic data tiles, and attempted to look up each segment id at `{tile}.segments[{id}]` -- to no avail. @kdiluca will be looking into this.

**Comment by louh** [comment]
This has been done for a while
