### ISSUE TITLE
Choose a date picker library.

### ISSUE THREAD

**Issue by louh** [opentraffic/analyst-ui#3]
As a user of this application, he or she would start by choosing a range of dates - a start date and an end date - so that we can display and visualize data that was collected between those days.

We're currently using [Semantic UI](https://semantic-ui.com/). It doesn't have a date picker component. (The previous app used a dropdown, and the unfinished prototype uses the React Material UI's [built-in date picker component](http://www.material-ui.com/#/components/date-picker).

There was a date picker component [proposed for Semantic UI](https://github.com/mdehoog/Semantic-UI-Calendar) but many other alternatives exist, for example:

- https://github.com/Hacker0x01/react-datepicker
- http://airbnb.io/projects/react-dates/
- http://react-day-picker.js.org/

(This is not an exhaustive list.)

Since the date picker lives outside of Semantic UI's core library we do not necessarily have to use the plugin for Semantic UI. However it might make sense if that plays the best with things. Other considerations include:

- Aesthetics - does it fit with the current UI or can it be styled to get us there?
- Popularity / support / updated - it should be something that many people use or are familiar with. (GitHub stars is one way of quickly gauging this.) It should have fairly consistent activity over the past 6 months so we can be sure someone is fixing bugs, etc.
- Plays well with toolchain - does it work with Webpack? Redux?
- Tested - are there tests provided? this helps protect against library upgrades breaking code.

**Comment by mkong0216** [comment]
I prefer the date picker component from airbnb. 
It's aesthetically pleasing and can be styled so that it matches the color palette we are using. 
Also it's pretty easy to use since you can choose both the start and end date at the same time and clearly see them on the same UI.

**Comment by louh** [comment]
Cool, let's give that a shot then! Let's try implementing Airbnb's date picker in the sidebar. When dates are picked, let's store them in Redux (we'll need a new reducer for this).

**Comment by louh** [comment]
Closed via https://github.com/opentraffic/analyst-ui/pull/13
