### ISSUE TITLE
Convert OSMLR segment IDs to level, tile, and segment index

### ISSUE THREAD

**Issue by louh** [opentraffic/analyst-ui#30]
```python
#!/usr/bin/env python

LEVEL_BITS = 3
TILE_INDEX_BITS = 22
SEGMENT_INDEX_BITS = 21

LEVEL_MASK = (2**LEVEL_BITS) - 1
TILE_INDEX_MASK = (2**TILE_INDEX_BITS) - 1
SEGMENT_INDEX_MASK = (2**SEGMENT_INDEX_BITS) - 1

def get_level(segment_id):
  return segment_id & LEVEL_MASK

def get_tile_index(segment_id):
  return (segment_id >> LEVEL_BITS) & TILE_INDEX_MASK

def get_segment_index(segment_id):
  return (segment_id >> (LEVEL_BITS + TILE_INDEX_BITS)) & SEGMENT_INDEX_MASK

print get_level(983044211424)
print get_tile_index(983044211424)
print get_segment_index(983044211424)
```

**Comment by louh** [comment]
@kevinkreiser I've converted this code into JavaScript, and learned something about how the right-shift operator works. It seems JavaScript maxes at 32-bit values, and this segment ID is greater than that. As a result, the right shift operator is giving different values in JavaScript vs Python.

Have you faced this before? Any thoughts?

**Comment by drewda** [comment]
@louh @kevinkreiser you may want to look at https://github.com/dcodeIO/long.js , https://github.com/peterolson/BigInteger.js , or other alternatives listed on NPM

**Comment by louh** [comment]
Thanks, @drewda . Going with BigInteger.js.

**Comment by louh** [comment]
Resolved in https://github.com/opentraffic/analyst-ui/commit/f747db6916cfae1911e28d0df5af9a22f6d72ff6
