### ISSUE TITLE
Allow users to "name" a view.

### ISSUE THREAD

**Issue by louh** [opentraffic/analyst-ui#47]
e.g. a selected region or route might have a name for it, to help ID the view later. I would probably just extend it to a name for the entire state of the application (what's contained in the URL string).

**Comment by mkong0216** [comment]
Can you explain more about the context/reasoning behind needing to name a view? Would this be found on the sidebar from the very beginning, when the user selects a region/route, or when exporting the data?

**Comment by louh** [comment]
This came as a comment from Kevin Webb yesterday. He was talking about it in terms of naming the region/route, but I think it might be more useful as a name for the entire view. Imagine if you generated more than one analysis and you send a list of URLs to someone. Then you need to tell your colleague to look at a specific analysis. How do you say which one it is? If a user can specify a name, they can call it "My Awesome Analysis No.1" or "Manila - Bonifacio Drive Rush Hour Study" or something, and it'll be clearer which one to look at.

There may be a few different options for where to put it -- perhaps at the top of the sidebar, or near the bottom, near Export.

**Comment by louh** [comment]
Similarly to what we did with Tangram Play / Tangram Frame, we could use the name in the document title to differentiate multiple tabs from each other, and make it easier to bookmark.

**Comment by mkong0216** [comment]
Not quite sure how the UI should look like for this. I currently just have a segment section on the sidebar with an input component and a submit button. Should there be anything else? Like once the input is submitted, the url will update and the document title as well but should the input be bolded or something to show that it was submitted? Or should this be a modal where once submitted the modal closes?

**Comment by louh** [comment]
I like the idea of editing in place. Here's an idea to try: look at the repo description at the top of a GitHub repository (e.g. at https://github.com/opentraffic/analyst-ui). The description is just text but there is an edit button. When you edit the text it turns into an input box. When you click save or cancel it turns into the new text (or reverts to the old one). The act of turning a input box into text (toggling edit mode on or off) indicates whether something is "submitted." Let me know what you think!

**Comment by mkong0216** [comment]
Oh! That sounds and looks better than what I was doing. Question then, should this component start out as an input box and then turn into a text with an edit button once the user puts his/her view name or should it start as text (maybe starting with 'Untitled Analysis' or something like that) with an edit button?
