### ISSUE TITLE
Add geolocation (search)

### ISSUE THREAD

**Issue by louh** [opentraffic/analyst-ui#5]
There is no location search in previous versions of the UI. You could select a region, but search would allow looking for specific streets, neighborhoods, etc.

We should incorporate Mapzen Search for this functionality.

There are two options for adding a search bar:

1) Use the [leaflet-geocoder-mapzen](https://github.com/mapzen/leaflet-geocoder) library. There are a couple of limitations with this approach: it's not in React, so we will need to work around this, including any interaction coming from search results with the map and the data store. Secondly, it means the UI must live on the map itself.

2) Use the [react-autosuggest](https://github.com/moroshko/react-autosuggest) library. This is React, so it will integrate with the app better, and we can decide to put the search bar anywhere -- on the map, or on the sidebar area. However, we will need to write all of the logic for integrating with Mapzen Search. Note that this is how [Tangram Play](https://github.com/tangrams/tangram-play/blob/master/src/js/components/MapPanelLocationBar.jsx) does it.

When a location is selected via the search bar, the information from Mapzen Search should be saved in the Redux store and the map location should be updated.

**Comment by mkong0216** [comment]
I'm thinking of using the react-autosuggest library to add a search bar. It will be easier to integrate with the app better and I think the ability to put the search bar anywhere is nice. 
Since Tangram Play already uses this, can I reuse code from there for some of the same things?

**Comment by louh** [comment]
Absolutely! I imagine there may be some minor differences in implementation, but definitely feel free to use Tangram Play as a reference to begin with.

**Comment by mkong0216** [comment]
After selecting the location from the search bar, I made it so that the map updates its center to the selected location. Should I also zoom in on the location? If so, what should I change the zoom to be?

**Comment by louh** [comment]
Closed via #18, #19
