### ISSUE TITLE
Incorporate time frames for data availability.

### ISSUE THREAD

**Issue by louh** [opentraffic/analyst-ui#6]
v2 feature request: We should show data availability for a given location, so you know the timeframe of the data available ("data spans x dates")

Still TBD: where and how this data is being stored. However, we can prepare for this on the front-end.

1) In the Redux data store, add some place to store the start and end dates of a range for data availability, and make the action creators/reducers necessary that some component in the future can use to update this information.
2) In the date picker component, it should be rendered such that dates outside the available time frame cannot be selected, if the range is available. If no data availability range is available, there is no boundary on what dates can be selected.
2b) Corollary: should a user never be able to select past "today"?
3) Inside the date picker component, but above or below the actual date picker elements, add a text note stating data availability range, if available.

**Comment by drewda** [comment]
Related: https://github.com/opentraffic/datastore/issues/40

**Comment by mkong0216** [comment]
Using the airbnb's react-dates Date Picker component, I can add a info panel below the calendar if needed to state the date availability range and define what dates will be allowed to be chosen through their props if need be. 

I'm thinking that the information collected for the Open Traffic won't know things about anything past "today" so maybe we should only have the option to choose past days?

**Comment by louh** [comment]
This sounds good, @mkong0216!

**Comment by louh** [comment]
@drewda to provide location of data

**Comment by drewda** [comment]
@louh @mkong0216: here are examples from Greg:
- http://bl.ocks.org/anonymous/raw/0c38999125e505baecfce3fe2dbcd0b9/
- http://bl.ocks.org/anonymous/raw/a68063af4e5d177c72d081eced9ca47b/

@gknisely: what will be the stable URL where the coverage map file will live in the future?

**Comment by gknisely** [comment]
it lives with the ref tile bucket

https://s3.amazonaws.com/referencetiles-prod/coverage_map.geojson

**Comment by drewda** [comment]
Two ideas for how to use this:

1. display the GeoJSON layer on the map when user arrives in Analyst UI, hide layer once user picks an analysis mode
2. use start/end dates in each polygon to control which weeks can be selected in the calendar date picker

**Comment by mkong0216** [comment]
So I've been working on this and I've got the GeoJSON to show on the map and it gets removed once user picks an analysis mode, but I'm wondering what you want it to do when the user is done with the analysis and clicks 'clear analysis'? Should we add the GeoJSON back onto the map? 
Also, when the page gets refreshed with the newly selected region or route, do you want to show the GeoJSON again or is it always hidden when an analysis mode is selected? 

Or maybe there should be a button that allows the user to show the geojson layer if they wanted it?

**Comment by drewda** [comment]
Sounds good to have a button to toggle the coverage layer. Once the user has begun clicking the map to draw a route or region query, you can automatically toggle off the layer. And if the user refreshes to a URL with a query, then the layer will also automatically be toggled off. How's that sound?

**Comment by mkong0216** [comment]
Sounds good! Thanks!

**Comment by mkong0216** [comment]
Closed via pull #149
