### ISSUE TITLE
If an edge has more than one traffic_segment, take a percentage of the encoded polyline

### ISSUE THREAD

**Issue by louh** [opentraffic/analyst-ui#61]
When looking at `edges` from `trace_attributes`, each `edge` contains a `traffic_segments` property that contains zero, one, or more `segments` associated with an OSMLR id. OSMLR segments and Valhalla edges do not _necessarily_ have a 1:1 relationship: that is, they do not necessarily share the same endpoints or length. When an OSMLR `segment` does not begin or end at the same endpoint of a Valhalla `edge` (or go beyond it), there will be more than one `segment` and each one will have a `start_percentage` and `end_percentage` value between `0` and `1`. As a result, to display the correct values for the `edge`, one must split it up according to these percent values and generate individual polylines for each `segment` in its place.

How does one take a percentage of an encoded polyline?

> One must decode the polyline, find the portion of the polyline that applies to that `edge` (`begin_shape_index` and `end_shape_index`), then use the length of that edge and the percentage along to interpolate over the shape of that indivdual edge to a certain position. It will require a few helper functions for distance computations and linear combinations in spherical coordinates. It's not too bad but it's also not exactly trivial

(via @kevinkreiser)

> For what its worth the C++ Distance computation looks like this:

```c
RAD_PER_DEG = PI / 180.0
kRadEarthMeters = 6378160.187

// Calculates the distance between two lat/lng's in meters. Uses spherical
// geometry (law of cosines).
float PointLL::Distance(const PointLL& ll2) const {
  // If points are the same, return 0
  if (*this == ll2)
    return 0.0f;

 // Delta longitude. Don't need to worry about crossing 180
  // since cos(x) = cos(-x)
  double deltalng = (ll2.lng() - lng()) * RAD_PER_DEG;
  double a = lat() * RAD_PER_DEG;
  double c = ll2.lat() * RAD_PER_DEG;

 // Find the angle subtended in radians (law of cosines)
  double cosb = (sin(a) * sin(c)) + (cos(a) * cos(c) * cos(deltalng));

 // Angle subtended * radius of earth (portion of the circumference).
  // Protect against cosb being outside -1 to 1 range.
  if (cosb >= 1.0)
    return 0.00001f;
  else if (cosb < -1.0)
    return kPi * kRadEarthMeters;
  else
    return (float)(acos(cosb) * kRadEarthMeters);
}
```

> You would basically walk the edge's shape (from `begin_shape_index` and accumulate distance until you exceed the distance you want (based on percentage). the desired point is along the line between the prior point and the point that exceeds the distance

**Comment by drewda** [comment]
@kdiluca or @dgearhart, do you if this is still an open issue with the way Analyst UI renders OSMRL segments? Or, if all the OSMLR segments are being rendered properly for your route requests, we can just close this.

**Comment by kdiluca** [comment]
We are all good!

**Comment by kdiluca** [comment]
Actually, I answered too quickly.  We'll need to test this more.

**Comment by dnesbitt61** [comment]
Need to find a long edge with multiple segments and verify.

**Comment by kdiluca** [comment]
I've confirmed that the Analyst UI is not rendering the OSMLR segments correctly when there are multiple segments for an edge.  I'm going to try to implement this and I've reached out to Meghan for feedback on how she did this in the Mobility Explorer.  Currently waiting to hear back.
Example: http://opentraffic-ui.netlify.com/?lat=14.6646&lng=120.9998&zoom=16.7500&startDate=1483246800000&endDate=1483851599999&df=0%2F1&hf=17%2F18&waypoints=14.6587%2F121.0004%2C14.6773%2F121.0007
We should see both segments  268267703160 & 268301257592 but UI is only displaying 268267703160.

**Comment by kdiluca** [comment]
Actually I've found in the route.js logic where this needs to happen and will implement it.  We also need to correct this for segments over multiple edges.  WIP
