### ISSUE TITLE
Add a route selection mode.

### ISSUE THREAD

**Issue by louh** [opentraffic/analyst-ui#7]
This duplicates the current functionality from [traffic-engine-app](https://github.com/opentraffic/traffic-engine-app), but we should use Mapzen routing services instead of OpenTripPlanner.

- Points can be added to a route by clicking on the map.
- What happens when a point is selected on a spot that cannot be routed to? Route to nearest routable spot?
- Should points be selectable by address? If so, this may affect how we implement #5.
- Instead of having a floating "undo" button, let's create better UI for removing points. I am not sure if clicking to remove points is ideal either. Destroying a point should have slightly more friction than creating a point.
- Is the route created from Valhalla (e.g. Mapzen Turn-by-Turn) or directly from OSMLR? Either way - the end result is OSMLR tiles, which we then visualize on the map (for the first stage, only show it in 1 color).

**Comment by dnesbitt61** [comment]
For now we would use Mapzen Turn-by-Turn to generate a route, but ultimately we will use a traffic enabled Valhalla instance hosted on Open Traffic servers.
