### ISSUE TITLE
geometry tiles: cache these

### ISSUE THREAD

**Issue by louh** [opentraffic/analyst-ui#85]
Currently, OSMLR geometry tiles are fetched and merged all at once. This is inefficient because we cannot cache tiles! Each new request (even after selecting a new time boundary) requires a new download of all geometry tiles.

We should be able to cache each tile just using its suffix path (e.g. `0/002/415`) as an index. If we have it in memory, return it, and only retrieve geometry tiles not in the cache.

Instead of having `fetchOSMLRGeometryTiles()` responsible for merging them, let's have them merged during the view, just before features are filtered to the ones inside the bbox.

**Comment by mkong0216** [comment]
Sorry, you probably already explained this to me but the `cacheTiles()` function that you're working on in the lou/data-cache branch is not the one you want me to use for the OSMLR geometry tiles, right? I'm supposed to make another function similar to that? Also are we merging before I call `withinBbox` or before I set the data source for tangram?

**Comment by louh** [comment]
Oof, the `lou/data-cache` branch is super old. I'll clean this up.

You can refer to the `cacheTiles()` currently in `data.js` (https://github.com/opentraffic/analyst-ui/blob/ab9b255c24d5139f1726fde2b598af5b792ac99c/src/app/data.js#L64), but yeah, I think you would set up another one separately for the geometry tiles, at least for now. Sometime later we can think about how to consolidate a cache, if we need to.

**Comment by louh** [comment]
> Also are we merging before I call withinBbox or before I set the data source for tangram?

I think you would merge the tiles at whatever moment is easiest for processing the features, which _I think_ would be before calling `withinBbox` -- but give it a try, see if that works.

**Comment by louh** [comment]
Done
