### ISSUE TITLE
Determine URL state and routing strategy.

### ISSUE THREAD

**Issue by louh** [opentraffic/analyst-ui#9]
We will need to store the minimum amount of information required to recover the state of the application in the URL string. This includes (but not an exhaustive list, yet):

- Map view (lat, lng, zoom)
- Route or network mode?
  - Selected route, if any
  - Selected region for network, if any
- Date ranges
- Time filters
- View options

Certain actions in the UI may create new history entries. When this does, the user expects back/forward to "just work." Ensure that the routing strategy adopted does not break browser navigation.

For consideration: [react-router](https://github.com/ReactTraining/react-router)

**Comment by mkong0216** [comment]
Should Date ranges be in unix timestamp or just month/date? 
Also which actions should create new history entries? Not really sure what should be expected when using back/forward

**Comment by louh** [comment]
Dates don't need to be human readable in the URL, so they only need to contain enough information to recover state. Unix timestamps are an easy format to store and read from. Other date formats might need a little more instruction to read from and write to, but you can have a much shorter string, in case URL length is a concern. Since I don't think it is, I'd say Unix timestamps are easier and do the job just fine.

As for actions that create history entries: yeah, we don't know yet what people expect when back/forward is clicked. We might need to do this later after we have more of the application done, so that we can get some feedback about expectations.

**Comment by mkong0216** [comment]
We currently have the option to select routes where we have a start marker, end marker, and an unlimited number of middle markers. The start marker's lat and lng as well as the end marker's lat and lng should be remembered by the url query string, but what about the middle markers? 

On one hand, I can see how users might want to take a specific route to their end destination which leads to the use of middle markers and the importance of the middle markers' lat/lng to be remembered in the URL (for when they share the URL). On the other had, the number of middle markers used is unlimited, so are we to remember every lat/lng of each middle marker. How should we do this? 

I'm leaning towards only adding start lat/lng and end lat/lng to the URL query string, but just wondering what others might think.

**Comment by louh** [comment]
Closing this now, we'll revisit history navigation later.
